# Generated by Django 5.2.4 on 2025-07-15 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_passwordvault'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_cyber_admin',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_normal_user',
        ),
        migrations.RemoveField(
            model_name='passwordvault',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='passwordvault',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
